### PR TITLE
add no-unused-expressions with do expressions support

### PR DESCRIPTION
**Pull request by lyleunderwood**
/cc #13 
I haven't really done any work with babel's AST before, so I'm sure I'm missing a ton of cases.

### CODE REVIEW

**Comment by lyleunderwood** [comment]
Also wasn't really sure whether this should be behind an option or not.

**Comment by donavon** [comment]
any progress on this?

**Comment by lyleunderwood** [comment]
@donavon thanks for reminding me about this.

I went ahead and added an option to turn support for do expressions off and updated the README. If anything is blocking this from being merged please let me know.

**Comment by iskilled** [comment]
I'm trying to test this PR, but I'm not sure how to set it up.

I've fetched the code and then added it to my project by using:
`npm instal --save-dev <PATH>/eslint-plugin-babel`
 which was added to my package.json as:
`"eslint-plugin-babel": "file:../../eslint-plugin-babel",`

I then edited my .eslintrc.js file to add the babel plugin and the no-unused-expressions rule, but when I run eslint I still get the error.


<details><summary>My .eslintrc.js file:</summary><p>

```javascript
module.exports = {
  "parser": "babel-eslint",
  "extends": "airbnb",
  "plugins": [
    "babel"
  ],
  "rules": {
    "object-curly-spacing": ["warn", "never"],
    "func-names": "off",
    "space-before-function-paren": ["error", "never"],
    "max-len": ["error", 120, 4],
    "no-unused-vars": ["error", {"argsIgnorePattern": "next"}],
    "import/prefer-default-export": "off",
    "comma-dangle": ["error", {
      "arrays": "always-multiline",
      "objects": "always-multiline",
      "functions": "ignore"
    }],
    "import/no-extraneous-dependencies": [
    "error", {
       "devDependencies": true, 
       "optionalDependencies": false, 
       "peerDependencies": false, 
       "packageDir": "./"
    }],
    "babel/no-unused-expressions": 1
  }
};
```

</p></details>


Any help would be very welcome.

**Comment by iskilled** [comment]
Ok, so after some validations I'm actually already testing this version of the plugin. 
That said, I'm still getting the no-unused-expressions error when using `do { ... }` expressions.

Code:
```javascript
level: do {
        if (process.env.NODE_ENV === 'testing') {
          'error'; // eslint-disable-line
        } else if (process.env.NODE_ENV === 'production') {
          'info'; // eslint-disable-line
        } else {
          'debug'; // eslint-disable-line
        }
      }
```

For each of the comments removed eslint will produce an error:
```
  11:11  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  13:11  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  15:11  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
```

**Comment by lyleunderwood** [comment]
@iskilled make sure you're using the `eslint` executable from your `node_modules` and not a globally installed one (run it directly from `./node_modules/.bin/eslint` if unsure). Here's all the relevant stuff from my `package.json`. Your example seems to be working fine when I paste it into a file in my project.

```javascript
    "eslint": "^3.8.1",
    "eslint-config-airbnb": "^12.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-babel": "https://github.com/lyleunderwood/eslint-plugin-babel.git#do-expressions",
    "eslint-plugin-flowtype": "^2.21.0",
    "eslint-plugin-fp": "^2.3.0",
    "eslint-plugin-import": "^2.0.1",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.4.1",
```

```javascript
  "eslintConfig": {
    "extends": [
      "airbnb",
      "plugin:flowtype/recommended"
    ],
    "parser": "babel-eslint",
    "plugins": [
      "import",
      "flowtype",
      "babel",
      "fp"
    ],
    "env": {
      "browser": true
    },
    "rules": {
      "new-cap": [
        2,
        {
          "capIsNewExceptions": [
            "Map",
            "List"
          ]
        }
      ],
      "no-unused-expressions": 0,
      "babel/no-unused-expressions": 2,
      "import/no-extraneous-dependencies": [
        "error",
        {
          "devDependencies": [
            "**/*.test.js",
            "**/*.test.jsx",
            "**/*.stories.js",
            "**/*.stories.jsx"
          ]
        }
      ],
      "fp/no-mutation": "error",
      "fp/no-arguments": "error",
      "fp/no-delete": "error",
      "fp/no-let": "error",
      "fp/no-loops": "error",
      "fp/no-mutating-assign": "error",
      "fp/no-mutating-methods": "error"
    }
  },
```

**Comment by iskilled** [comment]
I updated the following in my .eslintrc.js:
```javascript
"babel/no-unused-expressions": 1
```
to:
```javascript
"no-unused-expressions": 0,
"babel/no-unused-expressions": 2
```
and now it is working properly. Thanks!

**Comment by Javran** [comment]
any news from maintainers?

**Comment by lyleunderwood** [comment]
Nothing on my end, just waiting.

**Comment by mackenzie-orange** [comment]
I've been watching this PR for a month now, and no news. Is there a hold up? 

I'm pretty excited about this getting merged. Do-expressions are unusable in my codebase because of eslint rules, until this gets merged!

**Comment by lyleunderwood** [comment]
@mackenzie-orange for want of a better option, you can do what I do. My `eslint-plugin-babel` record looks like this in my `package.json`:

```json
"eslint-plugin-babel": "https://github.com/lyleunderwood/eslint-plugin-babel.git#do-expressions",
```

Of course in this scenario you're sort of beholden to me to not somehow break this repo. If that's a concern then you can just fork it to your own account and reference your own branch.

The other problem with this approach is that the branch won't get updates unless manually rebased.

**Comment by existentialism** [comment]
@lyleunderwood sorry for the delay, but if you're interested, can you update this now that we've moved to using `eslint-plugin-composer`?

**Comment by lyleunderwood** [comment]
@existentialism Done.

I rebased on 5.0.0 and implemented in terms of `eslint-rule-composer`. I also removed my `allowDoExpressions` option because I'm not sure how I would even get the option in the context of the composer, and it currently serves essentially the same purpose as just enabling / disabling the plugin-specific rule.

**Comment by existentialism** [comment]
@lyleunderwood yeah, accessing options inside `filterReports` won't land until https://github.com/not-an-aardvark/eslint-rule-composer/pull/1

**Comment by existentialism** [comment]
@lyleunderwood this was released in 5.1.0! thanks again!

**Comment by lyleunderwood** [comment]
Cool, thanks.

**Pull request merged**
