### PR TITLE
Camelcase - support for optional chaining

### PR DESCRIPTION
**Pull request by villesau**
Optional chaining checks fails in the main repo, this PR reimplements (copy&paste over) the rule, and fixes the issues pointed in tests. tests are same as in main repo plus one added test for optional chaining. I wanted to keep changes as minimal as possible while satisfying every spec the rule has.

Using eslint-rule-composer didn't seem to be feasible since the implementation (e.g in case of duplicate checks) varies, and even more tests failed when just passing the rule trough it. 

Easiest way to review this is to go commit by commit. First one is just copy&paste from eslint & some wire up.

ref: https://github.com/eslint/eslint/issues/10848

### CODE REVIEW

**Comment by villesau** [comment]
@existentialism @hzoo is there something that I could do to get this reviewed faster?

**Comment by diondirza** [comment]
Any progress on this guys?

**Comment by existentialism** [comment]
@villesau sorry for delay, been super swamped with work and @hzoo is at a conf. will try to look at this today or tomorrow!

**Comment by villesau** [comment]
@existentialism have you had time to go this trough? :)

**Comment by existentialism** [comment]
@villesau sorry again for the delay, landing once this goes green

**Comment by radoi90** [comment]
Hey guys this doesn't seem to be pushed to npm, is that on purpose?

**Comment by villesau** [comment]
true. @existentialism could this be published in npm?

**Comment by existentialism** [comment]
@villesau released as 5.3.0! thanks again!

**Pull request merged**
