### PR TITLE
Add allow-decorator-macro rule as an exception to no-undef

### PR DESCRIPTION
**Pull request by ghost**
Addresses issue raised in #26.

Adds the rule `allow-decorator-macro` as an exception to `no-undef` If the rule `allow-decorator-macro` is set to true the following code will not raise an `no-undef` warning:

``` javascript
function myDecorator() { }

var myObject = {
  @myDecorator myProperty
};
```

### CODE REVIEW

**Comment by jquense** [comment]
hey there, sorry for the delay, been busy!

I'm sorry...i have no idea what this is. What is this pattern/exception enabling aside from a reference to a variable that doesn't exist? I'm sure you have a good reason but I am missing a bit of the context here.

**Comment by jquense** [comment]
and maybe a further question: why do you think this is a good spot for this rule vs some independent package?

**Comment by devinus** [comment]
@jquense 

screen shot 2015-12-11 at 1 06 42 am

**Comment by jquense** [comment]
@devinus thanks but I understand why the error occurs and where, what I don't understand is why we should add an exception when the error is correct,

**Comment by hzoo** [comment]
Maybe it would be better as a custom rule?

**Comment by brancusi** [comment]
Would also like to know how I could squash this exact error. Using the same ember addon.

**Comment by linearza** [comment]
This might be of value: https://github.com/ember-cli/ember-cli-eslint/issues/86

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).

**Pull request closed without merging**
