### PR TITLE
Added support for decorators in the new-cap rule.

### PR DESCRIPTION
**Pull request by mathieumg**
Pretty self-explanatory!

### CODE REVIEW

**Comment by jquense** [comment]
thanks!

**Comment by AlexKVal** [comment]
Nice :+1:

**Comment by davewasmer** [comment]
Just curious - why is the capitalization required?

**Comment by mathieumg** [comment]
Because technically the lowercase ones don't get caught by this rule (http://eslint.org/docs/rules/new-cap)

**Pull request merged**
