### PR TITLE
Introduce camelcase "allow" option from eslint/eslint

### LINKED ISSUE #186: camelcase support "allow" pattern option from eslint base
https://eslint.org/docs/rules/camelcase#allow

Original test cases from eslint:

https://github.com/eslint/eslint/blob/41b1e4308c1cb01c8b00cc8adc36440e77854117/tests/lib/rules/camelcase.js#L200-L215

https://github.com/eslint/eslint/blob/41b1e4308c1cb01c8b00cc8adc36440e77854117/tests/lib/rules/camelcase.js#L687-L706

I think I can take a stab at PR today

### PR DESCRIPTION
**Pull request by TSMMark**
Closes #186

### CODE REVIEW

**Comment by TSMMark** [comment]
Just confirmed this works as expected in a medium sized React application codebase.

**Comment by TSMMark** [comment]
Hey @existentialism is there anything else I should do to get this merged and released?

**Comment by TSMMark** [comment]
Hey @hzoo is there anything else I should do to get this merged and released?

**Comment by existentialism** [comment]
@TSMMark thanks for the PR, we'll review it asap!

**Comment by mrtnzlml** [comment]
Hi @existentialism, I just wanted to kindly remind you about this PR in case you forgot. 🙂

**Comment by catskull** [comment]
I am also waiting on this to be merged before I can adopt this package. If it's just a simple matter of merging the PR let's make it happen!

**Comment by JayCanuck** [comment]
Any news on this PR? Would prefer to use all Babel plugin for this rule, but lack of support for `"allowed"` option is blocking myself and my team.

**Comment by keann** [comment]
+1 for the merge

**Comment by kaicataldo** [comment]
Thank you for the PR. Now that [@babel/eslint-plugin has been released](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint), we are making this repository read-only. If this is a change you would still like to advocate for, please reopen this in the [babel/babel monorepo](https://github.com/babel/babel).

**Pull request closed without merging**
