### PR TITLE
Future-proofing

### PR DESCRIPTION
**Pull request by evocateur**
My original goal was to remove the dependency on `babel-core@5`, since there's no actual usage of the module in this plugin (nor of the `helpers.js` file, wherein the only `require('babel-core')` is located). By doing this, we reduce the amount of cruft installed by npm when users update to babel 6.

I went through all the [dependents](https://www.npmjs.com/browse/depended/eslint-plugin-babel) of `eslint-plugin-babel`, and none of them are requiring `helpers.js`. Some of the dependents themselves depend on `babel-core`, but that's not a reason to keep it as a dependency of this module.

Incidentally, when running the tests after making my changes, I found weird errors related to the recent `Object.freeze()` shenanigans upstream in `eslint`. Theoretically, `eslint@1.10.1` should have reverted those breaking changes (first reported as breaking `eslint-plugin-react`), but it's a good idea to stop modifying the `context` object anyway, as the maintainers of `eslint` have expressed the intention of restoring that freeze in `eslint@2`.

### CODE REVIEW

**Comment by jquense** [comment]
many thanks!

**Comment by hzoo** [comment]
Looks good - should we do a major version bump in case?

**Comment by evocateur** [comment]
@hzoo I almost suggested that, just to be extra-safe. I'm cool either way.

**Comment by hzoo** [comment]
I think that would be best - published 3.0

**Comment by evocateur** [comment]
Thanks!

**Pull request merged**
