### PR TITLE
Update: Implement auto fix for object-curly-spacing (fixes #37)

### LINKED ISSUE #37: Implement auto fix functionality for object-curly-spacing rule eslint/eslint#3857
Ref eslint/eslint#3857

### PR DESCRIPTION
**Pull request by zaygraveyard**
cherry picked form eslint/eslint/commit/1dcca0c95b894a91dc466ab5692292a99f717d54

### CODE REVIEW

**Comment by jquense** [comment]
can you just rebase on the last PR and we should be good to go :) thanks alot

**Comment by zaygraveyard** [comment]
Yeah sure.
Happy to help ^^

**Comment by zaygraveyard** [comment]
Rebase done

**Comment by jquense** [comment]
thanks again!

**Pull request merged**
